### ISSUE TITLE
Delete this repo?

### ISSUE THREAD

**Issue by fanaugen** [blinkist/blinkist-deeplinks#3]
🚚  The source code for this HTML file has moved to [blinkist-infrastructure](https://github.com/blinkist/blinkist-infrastructure/blob/52372c6950c602af3dfeaf4a9f015ffa40ea31cb/terraform/environments/main/deeplinks-test.html), and the HTML page itself is uploaded to S3 and hosted via Cloudfront at https://deeplinks-test.blinkist.io

**Comment by fanaugen** [comment]
@tprzedmojski @philipphager this repo should be safe to delete

**Comment by poisonpie** [comment]
Hi guys,

for some reason I'm still subbed to this repo despite having been removed
from the Blinkist GH org.

Maybe take a look at this and remove me from all Blinkist related things?

Thanks and have a good one!

Franziska Ströbel

**Comment by philipphager** [comment]
@fanaugen Absolutely fine with me :)! Shall we archive or delete this repo?

**Comment by tprzedmojski** [comment]
👋
